require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should
